### ISSUE TITLE
PRACTICA DE HILOS EN CONSOLA C#

### ISSUE THREAD

**Issue by MariaJose-10** [SistemasTecTlaxiaco/practica-de-hilos-MariaJose-10#2]
[TOPICOS AVANZADOS_PRACTICA DE HILOS EN CONSOLA_MARIA JOSE LOPEZ LEYVA.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-MariaJose-10/files/8430729/TOPICOS.AVANZADOS_PRACTICA.DE.HILOS.EN.CONSOLA_MARIA.JOSE.LOPEZ.LEYVA.pdf)

[Practicahilo_MariaJoseLopezLeyva.zip](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-MariaJose-10/files/8430580/Practicahilo_MariaJoseLopezLeyva.zip)

**Comment by JoseABCruz** [comment]
CALIFICACION: 17.5%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
